export const links = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "ingredients",
    title: "Ingredients",
  },
  {
    id: "recomendations",
    title: "Recomendations",
  },
  {
    id: "recipes",
    title: "Recipes",
  },
];

export const ingredints = [
  {
    id: "spirits",
    title: "Spirits",
    structure: [
      {
        id: "brandy",
        title: "Brandy",
        structure: ["Applejack", "Brandy", "Calvados", "Cognac", "Pisco"],
      },
      {
        id: "gin",
        title: "Gin",
        structure: ["Genever", "Gin", "Old Tom Gin"],
      },
      {
        id: "mezcal",
        title: "Mezcal",
        structure: [
          "Mezcal",
          "Tequila Anejo",
          "Tequila Blanco",
          "Tequila Reposado",
        ],
      },
      {
        id: "rum",
        title: "Rum",
        structure: [
          "Aged Rum",
          "Blackstrap Rum",
          "Cachaca",
          "Dark/ Black Rum",
          "Dark Jamacian Rum",
          "Demerara Rum",
          "Jamacian Aged Rum",
          "Overproof Aged Rum",
          "Overproof Black Rum",
          "Overproof Jamacian Rum",
          "Overproof White Rum",
          "Pineapple Rum",
          "White Rum",
        ],
      },
      {
        id: "vodka",
        title: "Vodka",
        structure: ["Lemon Vodka", "Vodka"],
      },
      {
        id: "whiskey",
        title: "Whisk(e)y",
        structure: [
          "Bourbon Whiskey",
          "Irish Whiskey",
          "Islay Whiskey",
          "Overproof Bourbon Whiskey",
          "Overproof Rye Whiskey",
          "Rye Whiskey",
          "Scotch Whisky",
        ],
      },
    ],
  },
  {
    id: "liquerus",
    title: "Liquerus",
    structure: [
      {
        id: "amaro",
        title: "Amaro",
        structure: [
          "Amaro Averna",
          "Amaro Montenegro",
          "Amaro Nonino",
          "Amaro Ramazzotti",
          "Aperol",
          "Campari",
          "Cynar",
          "Fernet",
          "Fernet Brancamenta",
        ],
      },
      {
        id: "coffee",
        title: "Coffee",
        structure: ["Coffe Liquer", "Kahlua", "Mr.Black", "Tia Maria"],
      },
      {
        id: "cream",
        title: "Cream",
        structure: ["Amarula", "Baileys", "RumChata"],
      },
      {
        id: "creme",
        title: "Creme",
        structure: [
          "Creme de Banana",
          "Creme de Cacao",
          "Creme de Cacao Blanc",
          "Creme de Cassis",
          "Creme de Menthe",
          "Creme de Mure",
          "Creme de Noyaux",
          "Creme de Peche",
          "Creme de Violette",
        ],
      },
      {
        id: "fruit",
        title: "Fruit",
        structure: [
          "Apicot Liquer",
          "Black Raspberry Liquer",
          "Blue Curacao",
          "Cherry Heering",
          "Coconut Liquer",
          "Malibu",
          "Curasao",
          "Grand Marnier",
          "Limoncello",
          "Peach Schnapps",
          "Pear Liquer",
          "Sloe Gin",
          "Triple Sec",
        ],
      },
      {
        id: "herbal",
        title: "Herbal",
        structure: [
          "Benedictine",
          "Elderflower Liquer",
          "Suze",
          "Green Chartreuse",
          "Jagermeister",
          "Yellow Chartreuse",
        ],
      },
      {
        id: "otherLiqueres",
        title: "Other",
        structure: [
          "Absinthe",
          "Amaretto",
          "Sambuca",
          "Ginger Liquer",
          "Maraschino Liquer",
        ],
      },
    ],
  },
  {
    id: "wine",
    title: "Wine",
    structure: [
      {
        id: "aromatized",
        title: "Aromatized",
        structure: ["Cocchi Americano", "Lillet Blanc"],
      },
      {
        id: "port",
        title: "Port",
        structure: ["Ruby Port", "Tawny Port", "White Port"],
      },
      {
        id: "sparkling",
        title: "Sparkling",
        structure: ["Cava", "Champange", "Prosecco"],
      },
      {
        id: "vermouth",
        title: "Vermouth",
        structure: ["Blanc Vermouth", "Dry Vermouth", "Sweet Vermoutht"],
      },
      {
        id: "wines",
        title: "Wine",
        structure: ["Red Wine", "Rose Wine", "White Wine"],
      },
    ],
  },
  {
    id: "sweeteners",
    title: "Sweeteners",
    structure: [
      "Agave Syrup",
      "Brown Sugar Syrup",
      "Cardamon-Honey Syrup",
      "Cinnamon Syrup",
      "Cream of Cococnut",
      "Demerara Syrup",
      "Spice Honey Syrup",
      "Ginger Syrup",
      "Gomme Syrup",
      "Grenadine",
      "Honey Syrup",
      "Lime Cordial",
      "Maple Syrup",
      "Cola Syrup",
      "Orgeat",
      "Passionfruit Syrup",
      "Pineapple Syrup",
      "Pomegranate Syrup",
      "Raspberry Syrup",
      "Simple Syrup",
      "Mai Tai Syrup",
      "Vanila Syrup",
    ],
  },
  {
    id: "juices",
    title: "Juices",
    structure: [
      "Clamanto",
      "Cranberry Juice",
      "Grapefruit Juice",
      "Lemon Juice",
      "Lime Juice",
      "Mango Juice",
      "Orange Juice",
      "Passionfruit Juice",
      "Pear Juice",
      "Pineapple Juice",
      "Pomegranate Juice",
      "Strawberry Juice",
      "Tomato Juice",
    ],
  },
  {
    id: "fresh",
    title: "Fresh Produce",
    structure: [
      "Blackberries",
      "Cucumber",
      "Ginger",
      "Grapefruit",
      "Jalapeno Peppers",
      "Kiwi",
      "Lemon",
      "Lime",
      "Mandarin Oranges",
      "Mango",
      "Oranges",
      "Passionfruit",
      "Pears",
      "Pineapple",
      "Pomegranate",
      "Raspberries",
      "Strawberries",
      "Tangerines",
    ],
  },
  {
    id: "herbs",
    title: "Herbs & Spices",
    structure: [
      "Basil",
      "Cardamon",
      "Cinnamon",
      "Cloves",
      "Dried Bitter Orange Peel",
      "Lavender",
      "Mint",
      "Nutmeg",
      "Pepper",
      "Rosemary",
      "Vanilla",
    ],
  },
  {
    id: "bitters",
    title: "Bitters",
    structure: [
      "Angostura Bitters",
      "Boker`s Bitters",
      "Cacao Bitters",
      "Cardamon Bitters",
      "Celery Bitters",
      "Chocolate Bitters",
      "Grapefruit Bitters",
      "Orange Bitters",
      "Orinoco Bitters",
      "Peychaud`s Bitters",
      "Walnut Bitters",
    ],
  },
  {
    id: "pantry",
    title: "Pantry",
    structure: [
      "Almond Milk",
      "Aquafaba",
      "Brown Sugar",
      "Club Soda",
      "Coca-Cola",
      "Coconut Milk",
      "Coffee",
      "Demerara Sugar",
      "Eggs",
      "Ginger Beer",
      "Grapefruit Soda",
      "Heavy Cream",
      "Honey",
      "Maraschino Cherries",
      "Milk",
      "Olives",
      "Orange Blossom Water",
      "Root Beer",
      "Salt",
      "Sprite",
      "Tabasco",
      "Tonic Water",
      "Water",
      "White Sugar",
      "Worcestershire Sauce",
    ],
  },
];
